### ISSUE TITLE
Adding Metric Alarms To Allow Monitoring Across All Functions

### ISSUE THREAD

**Issue by jay72487** [base2Services/cfn-guardian#123]
Currently guardian doesn't seem to support alarms which lack a resource id and consist of just one Metric. Could you please add metric monitoring so that it is possible to monitor a specific metrics across the entire resource group. I.e The throttle metric for the lambda resource group  
![image](https://github.com/base2Services/cfn-guardian/assets/119831403/6f2335f2-8d7f-4e2f-b14c-9e4b41d5ba2a)
![image](https://github.com/base2Services/cfn-guardian/assets/119831403/7aeb2deb-0bd6-4962-a66b-b5f659f7100a)

**Comment by CarlosZambonii** [comment]
Hello! 👋 I came across this issue while looking for a good first contribution, and think it might already be resolved.

The `SearchExpression`/`SearchAggregation` feature added in #143 looks like it fully covers this use case — an alarm on a metric across an entire resource group, with no fixed `Dimensions`/resource id. I tested it locally with:

```yaml
Templates:
  Lambda:
    ThrottlesAcrossAllFunctions:
      SearchExpression: "SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Throttles\"', 'Sum', 60)"
      SearchAggregation: SUM
      Threshold: 100
```

and `cfn-guardian compile` produces a valid alarm with no dimensions, aggregating the Throttles metric across all Lambda functions:

```yaml
Metrics:
- Id: search_expression
  Expression: SEARCH('{AWS/Lambda,FunctionName} MetricName="Throttles"', 'Sum', 60)
  Period: 60
  ReturnData: false
- Id: aggregate
  Expression: SUM(search_expression)
  ReturnData: true
```

This matches what's shown in the screenshots above (CloudWatch's "Across All Functions" view). If I'm reading this right, this issue could probably be closed as resolved by #143 — happy to add this example to `docs/search_expressions.md` if that'd be useful, since it isn't currently listed as a supported use case there.

Thanks for maintaining this project!
