### ISSUE TITLE
unable to override multiple loggroup alarms for a single loggroup

### ISSUE THREAD

**Issue by Guslington** [base2Services/cfn-guardian#31]
version: 0.6.5

the following config generates the error

```yaml
Resources:
  LogGroup:
  - Id: log-group
    MetricFilters:
    - MetricName: 'TimeoutError'
      Pattern: 'Connection Timed Out'
    - MetricName: 'ErorrLog'
      Pattern: 'error'
  - Id: log-group-2
    MetricFilters:
    - MetricName: 'TimeoutError2'
      Pattern: 'Connection Timed Out'
    - MetricName: 'ErorrLog2'
      Pattern: 'error'

Templates:
  LogGroup:
    TimeoutError:
      Threshold: 10
    ErorrLog:
      Threshold: 10
    TimeoutError2:
      Threshold: 10
    ErorrLog2:
      Threshold: 10
 ```
 
 ```
[*] Alarm TimeoutError2 for resource log-group has nil value for property MetricName
[*] Alarm ErorrLog2 for resource log-group has nil value for property MetricName
[*] Alarm TimeoutError for resource log-group-2 has nil value for property MetricName
[*] Alarm ErorrLog for resource log-group-2 has nil value for property MetricName
```

**Comment by Guslington** [comment]
This is happening because guardian assumes all resources in the `LogGroup` resource group have the same alarms as it does with all the other resource groups. Where as each resource defined under `LogGroup` generates alarms specific for that resource based upon the `MetricName`.

When the overrides are applied, they are applied to every resource defined in the `LogGroup` resource group and because the alarms are unique to the resource, guardian attempts to create the non existent alarms for the other resources.

The work around from the time being is to create a new LogGroup resource group for each log group you want to monitor.

```yaml
Resources:
  LogGroup:
  - Id: log-group
    MetricFilters:
    - MetricName: 'TimeoutError'
      Pattern: 'Connection Timed Out'
    - MetricName: 'ErorrLog'
      Pattern: 'error'
  LogGroupTwo:
  - Id: log-group-2
    MetricFilters:
    - MetricName: 'TimeoutError2'
      Pattern: 'Connection Timed Out'
    - MetricName: 'ErorrLog2'
      Pattern: 'error'
      
Templates:
  LogGroup:
    TimeoutError:
      Threshold: 10
    ErorrLog:
      Threshold: 10
  LogGroupTwo:
    Inherit: LogGroup
    TimeoutError2:
      Threshold: 10
    ErorrLog2:
      Threshold: 10
 ```
