### ISSUE TITLE
AlarmActions are not always being overridden

### ISSUE THREAD

**Issue by Guslington** [base2Services/cfn-guardian#39]
using the following config to override all alarm actions

```yaml
Topics:
  Informational: arn:aws:sns:us-east-1:111111111111:slack
  Custom: arn:aws:sns:us-east-1:111111111111:custom-alerts

Templates:
  ApiGateway:
    GroupOverrides:
      AlarmAction: Informational
  AutoScalingGroup:
    GroupOverrides:
      AlarmAction: 
      - Informational
      - Custom
        
Resources:
  ApiGateway:
    - Id: dev
    - Id: test
  AutoScalingGroup:
    - Id: dev
    - Id: test
```

compiles alarms that contain the original alarm action such as critical or warning
