### ISSUE TITLE
error message when unknown alarm is overridden needs improvement

### ISSUE THREAD

**Issue by Guslington** [base2Services/cfn-guardian#60]
config

```yaml
Templates:   
  ApplicationTargetGroup:
    HealthyHostCount: # not an alarm for application target group
      Threshold: 1
```

Error message

```
/usr/local/bundle/gems/cfn-guardian-0.7.14/lib/cfnguardian/compile.rb:180:in `validate_resources': 1 errors found (CfnGuardian::ValidationError)
[*] Alarm HealthyHostCount for resource targetgroup/***/*** has nil value for property MetricName
    from /usr/local/bundle/gems/cfn-guardian-0.7.14/lib/cfnguardian/compile.rb:150:in `get_resources'
    from /usr/local/bundle/gems/cfn-guardian-0.7.14/lib/cfnguardian.rb:51:in `compile'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
    from /usr/local/bundle/gems/cfn-guardian-0.7.14/exe/cfn-guardian:4:in `<top (required)>'
    from /usr/local/bundle/bin/cfn-guardian:23:in `load'
    from /usr/local/bundle/bin/cfn-guardian:23:in `<main>'
```
