### ISSUE TITLE
Add functionality to substitute/map values in alarms.yaml

### ISSUE THREAD

**Issue by tarunmenon95** [base2Services/cfn-guardian#69]
**Issue:**
Add the ability for users to substitute values when defining parameters in the alarms.yaml.

**Example:**
In the following example. Custom tags are created which ideally would map to the corresponding Cluster & Service defined in the resources section. This perhaps could be done via a substitution or Ref.
```
Topics:
  EcsCycle: arn:aws:sns:ap-southeast-2:123456789123:guardian-ecs-service-cycle

Templates:
  ECSService:
    GroupOverrides:
      AlarmAction:
        - EcsCycle
      Tags:
        ecscycle:service: **MAPPED VALUE HERE**
        ecscycle:cluster:  **MAPPED VALUE HERE**

Resources:
    ECSService:
      - Cluster: asdf123-ecsec2-123456789-EcsCluster-asdf1234
         Id: adsf123-ecsservice-123456789-Service-asdf1234
```
