### ISSUE TITLE
Multiple/custom NRPE templates

### ISSUE THREAD

**Issue by mitchclarkebase2** [base2Services/cfn-guardian#82]
Currently if you try to create a custom NRPE template alongside the regular NRPE template the build will fail with the below error(s):

```
/usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/resources/nrpe.rb:7:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
--
47 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:95:in `new'
48 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:95:in `rescue in block (2 levels) in get_resources'
49 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:90:in `block (2 levels) in get_resources'
50 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:88:in `each'
51 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:88:in `block in get_resources'
52 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:87:in `each'
53 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:87:in `get_resources'
54 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian.rb:100:in `deploy'
55 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
56 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
57 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
58 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
59 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/exe/cfn-guardian:4:in `<top (required)>'
60 | from /usr/local/bundle/bin/cfn-guardian:23:in `load'
61 | from /usr/local/bundle/bin/cfn-guardian:23:in `<main>'
62 | /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:91:in `block (2 levels) in get_resources': uninitialized constant CfnGuardian::Resource::NrpeDev (NameError)
63 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:88:in `each'
64 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:88:in `block in get_resources'
65 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:87:in `each'
66 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian/compile.rb:87:in `get_resources'
67 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/lib/cfnguardian.rb:100:in `deploy'
68 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
69 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
70 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
71 | from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
72 | from /usr/local/bundle/gems/cfn-guardian-0.8.4/exe/cfn-guardian:4:in `<top (required)>'
73 | from /usr/local/bundle/bin/cfn-guardian:23:in `load'
74 | from /usr/local/bundle/bin/cfn-guardian:23:in `<main>'
```

Here's an example of the config:

```
Nrpe:
  - Environment: Prod
    VpcId: vpc-xxxxxxx
    Subnets:
      - subnet-xxxxxxx
      - subnet-xxxxxxx
    Hosts:
    - Id: x.x.x.x
      Commands:
        - check_disks
NrpeDev:
  - Environment: Dev
    VpcId: vpc-xxxxxxx
    Subnets:
      - subnet-xxxxxxx
      - subnet-xxxxxxx
    Hosts:
    - Id: x.x.x.x
      Commands:
        - check_disks
    
Templates:
  NrpeDev:
    Inherit: Nrpe
    GroupOverrides:
      AlarmAction: Warning
```

I believe this was possible in cfn-monitor, so it would be great if we could also do it in guardian. It may already be possible but just in a different way than other normal resource templates. If that is the case then I am happy to close this.
