### ISSUE TITLE
incorrect alarms added maintance groups

### ISSUE THREAD

**Issue by Guslington** [base2Services/cfn-guardian#95]
The first resource in the a resource group is added to the maintenance group instead of the specified resource when the resource is a part of a resource groups with multiple resources.

example alarms.yaml

```yaml
Resources:
  DynamoDBTable:
  - Id: table-1
  - Id: table-2
  - Id: table-3
  - Id: table-4
MaintenanceGroups:
  DynamoReadUsage:    # doesn't work
    Schedules:
      Disable: '55 23 * * ? *'
      Enable: '20 0 * * ? *'
      Debug: true
    DynamoDBTable:
      DynamoDBReadUsage:
      - Id: table-4
```
